CREATE TABLE EMPLOYE (
  idEmploye INT AUTO_INCREMENT,
  nomEmploye VARCHAR(42) NOT NULL,
  prenomEmploye VARCHAR(42) NOT NULL,
  mailEmploye VARCHAR(42) NOT NULL,
  mdpEmploye VARCHAR(42) NOT NULL,
  dateArrivee DATETIME,
  dateDepart DATETIME,
  typeEmploye TINYINT DEFAULT 0,
  idLigue INT NOT NULL,
  PRIMARY KEY (idEmploye)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LIGUE (
  idLigue INT AUTO_INCREMENT,
  nomLigue VARCHAR(42) NOT NULL,
  PRIMARY KEY (idLigue)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE EMPLOYE ADD FOREIGN KEY (idLigue) REFERENCES LIGUE (idLigue);